export const CREATE_DICTIONARY = 'CREATE_DICTIONARY';
export const EDIT_DICTIONARY = 'EDIT_DICTIONARY';
export const SAVE_DICTIONARY = 'SAVE_DICTIONARY';
export const DELETE_DICTIONARY = 'DELETE_DICTIONARY';
export const APPLY_DICTIONARY = 'APPLY_DICTIONARY';
